version: '3.8'
services:
  api:
    environment:
      - NODE_ENV=production
      - SERVER_PORT=$SERVER_PORT
    build:
      context: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always

  postgres:
    container_name: statements-api-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge